# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Microservice
  licenses: MIT
  images: |
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r33
    - name: ms
      image: docker.io/laragis/ms:0.1.0
apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Helm chart Boilerplate contains all the boilerplate you need to create a Helm chart.
home: https://laragis.vn
icon: https://laragis.vn/assets/stacks/ms/img/ms-stack-220x234.png
keywords:
- application
- http
- web
maintainers:
- name: Truong Thanh Tung.
  url: https://github.com/laragis/charts
name: ms
sources:
- https://github.com/laragis/charts/tree/main/laragis/ms
- https://github.com/laragis/containers/tree/main/laragis/ms
version: 0.1.0
